# -*- coding: utf-8 -*-
"""features.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cbTctIl2Fw88YDJ5rVQg3P3-7boq4AZk
"""

def add_growth_features(df):
    df = df.copy()
    df['yoy_growth_pct'] = df['retail_index'].pct_change(12) * 100
    df['mom_growth_pct'] = df['retail_index'].pct_change()
    return df