# -*- coding: utf-8 -*-
"""pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HEA9eRHtfMpe9Di5oA5gJDNEN58LR7DA
"""

from ingestion import load_data
from cleaning import clean_data
from features import add_features
from forecasting import train_model, forecast

df_raw = load_data()
df_clean = clean_data(df_raw)
df_feat = add_features(df_clean)

model = train_model(df_feat)
forecast_df = forecast(model)

forecast_df.to_csv("data/forecasts/forecast.csv", index=False)